/**
 * generated by Xtext
 */
package org.omg.qpe.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.omg.qpe.QPERuntimeModule;
import org.omg.qpe.QPEStandaloneSetup;
import org.omg.qpe.ide.QPEIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class QPEIdeSetup extends QPEStandaloneSetup {
  @Override
  public Injector createInjector() {
    QPERuntimeModule _qPERuntimeModule = new QPERuntimeModule();
    QPEIdeModule _qPEIdeModule = new QPEIdeModule();
    return Guice.createInjector(Modules2.mixin(_qPERuntimeModule, _qPEIdeModule));
  }
}
