/**
 * generated by Xtext
 */
package org.omg.qpe.ide;

import org.omg.qpe.ide.AbstractQPEIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class QPEIdeModule extends AbstractQPEIdeModule {
}
