/**
 * generated by Xtext
 */
package org.omg.qpe;

import org.omg.qpe.AbstractQPERuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class QPERuntimeModule extends AbstractQPERuntimeModule {
}
