/**
 * generated by Xtext
 */
package org.omg.qpe;

import org.omg.qpe.QPEStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class QPEStandaloneSetup extends QPEStandaloneSetupGenerated {
  public static void doSetup() {
    new QPEStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
