/*
 * generated by Xtext
 */
package org.omg.qpe.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.omg.qpe.parser.antlr.internal.InternalQPEParser;
import org.omg.qpe.services.QPEGrammarAccess;

public class QPEParser extends AbstractAntlrParser {

	@Inject
	private QPEGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalQPEParser createParser(XtextTokenStream stream) {
		return new InternalQPEParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "QPE";
	}

	public QPEGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(QPEGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
