/*
 * generated by Xtext
 */
package org.omg.qpe.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractQPEScopeProvider extends DelegatingScopeProvider {
}
