/**
 * generated by Xtext
 */
package org.omg.qpe.scoping;

import org.omg.qpe.scoping.AbstractQPEScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class QPEScopeProvider extends AbstractQPEScopeProvider {
}
