/*
 * generated by Xtext
 */
package org.omg.qpe.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.omg.qpe.ide.contentassist.antlr.internal.InternalQPEParser;
import org.omg.qpe.services.QPEGrammarAccess;

public class QPEParser extends AbstractContentAssistParser {

	@Inject
	private QPEGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalQPEParser createParser() {
		InternalQPEParser result = new InternalQPEParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getPredicateAccess().getAlternatives(), "rule__Predicate__Alternatives");
					put(grammarAccess.getVALUEAccess().getAlternatives(), "rule__VALUE__Alternatives");
					put(grammarAccess.getLONGAccess().getAlternatives_1(), "rule__LONG__Alternatives_1");
					put(grammarAccess.getBOOLEANAccess().getAlternatives(), "rule__BOOLEAN__Alternatives");
					put(grammarAccess.getQPEAccess().getGroup(), "rule__QPE__Group__0");
					put(grammarAccess.getQueryNamespaceAccess().getGroup(), "rule__QueryNamespace__Group__0");
					put(grammarAccess.getQueryNamespaceAccess().getGroup_2(), "rule__QueryNamespace__Group_2__0");
					put(grammarAccess.getPathExpressionAccess().getGroup(), "rule__PathExpression__Group__0");
					put(grammarAccess.getQueryElementAccess().getGroup(), "rule__QueryElement__Group__0");
					put(grammarAccess.getQueryElementAccess().getGroup_0(), "rule__QueryElement__Group_0__0");
					put(grammarAccess.getQueryElementAccess().getGroup_3(), "rule__QueryElement__Group_3__0");
					put(grammarAccess.getQualifierAccess().getGroup(), "rule__Qualifier__Group__0");
					put(grammarAccess.getQualifierAccess().getGroup_2(), "rule__Qualifier__Group_2__0");
					put(grammarAccess.getClassifierPredicateAccess().getGroup(), "rule__ClassifierPredicate__Group__0");
					put(grammarAccess.getClassifierPredicateAccess().getGroup_0(), "rule__ClassifierPredicate__Group_0__0");
					put(grammarAccess.getAttributePredicateAccess().getGroup(), "rule__AttributePredicate__Group__0");
					put(grammarAccess.getAttributePredicateAccess().getGroup_0(), "rule__AttributePredicate__Group_0__0");
					put(grammarAccess.getReferencePredicateAccess().getGroup(), "rule__ReferencePredicate__Group__0");
					put(grammarAccess.getReferencePredicateAccess().getGroup_0(), "rule__ReferencePredicate__Group_0__0");
					put(grammarAccess.getLONGAccess().getGroup(), "rule__LONG__Group__0");
					put(grammarAccess.getDOUBLEAccess().getGroup(), "rule__DOUBLE__Group__0");
					put(grammarAccess.getQPEAccess().getQuerynamespacesAssignment_0(), "rule__QPE__QuerynamespacesAssignment_0");
					put(grammarAccess.getQPEAccess().getPathexpressionsAssignment_1(), "rule__QPE__PathexpressionsAssignment_1");
					put(grammarAccess.getQueryNamespaceAccess().getIRIAssignment_1(), "rule__QueryNamespace__IRIAssignment_1");
					put(grammarAccess.getQueryNamespaceAccess().getPrefixAssignment_2_1(), "rule__QueryNamespace__PrefixAssignment_2_1");
					put(grammarAccess.getPathExpressionAccess().getIsRelativeAssignment_0(), "rule__PathExpression__IsRelativeAssignment_0");
					put(grammarAccess.getPathExpressionAccess().getHeadAssignment_2(), "rule__PathExpression__HeadAssignment_2");
					put(grammarAccess.getQueryElementAccess().getQuerynamespaceAssignment_0_0(), "rule__QueryElement__QuerynamespaceAssignment_0_0");
					put(grammarAccess.getQueryElementAccess().getFeatureAssignment_1(), "rule__QueryElement__FeatureAssignment_1");
					put(grammarAccess.getQueryElementAccess().getQualifierAssignment_2(), "rule__QueryElement__QualifierAssignment_2");
					put(grammarAccess.getQueryElementAccess().getNextAssignment_3_1(), "rule__QueryElement__NextAssignment_3_1");
					put(grammarAccess.getQualifierAccess().getPredicateAssignment_1(), "rule__Qualifier__PredicateAssignment_1");
					put(grammarAccess.getQualifierAccess().getPredicateAssignment_2_1(), "rule__Qualifier__PredicateAssignment_2_1");
					put(grammarAccess.getClassifierPredicateAccess().getQuerynamespaceAssignment_0_0(), "rule__ClassifierPredicate__QuerynamespaceAssignment_0_0");
					put(grammarAccess.getClassifierPredicateAccess().getClassifierAssignment_1(), "rule__ClassifierPredicate__ClassifierAssignment_1");
					put(grammarAccess.getAttributePredicateAccess().getQuerynamespaceAssignment_0_0(), "rule__AttributePredicate__QuerynamespaceAssignment_0_0");
					put(grammarAccess.getAttributePredicateAccess().getAttributeAssignment_1(), "rule__AttributePredicate__AttributeAssignment_1");
					put(grammarAccess.getAttributePredicateAccess().getValueAssignment_3(), "rule__AttributePredicate__ValueAssignment_3");
					put(grammarAccess.getReferencePredicateAccess().getQuerynamespaceAssignment_0_0(), "rule__ReferencePredicate__QuerynamespaceAssignment_0_0");
					put(grammarAccess.getReferencePredicateAccess().getReferenceAssignment_1(), "rule__ReferencePredicate__ReferenceAssignment_1");
					put(grammarAccess.getReferencePredicateAccess().getQualifierAssignment_2(), "rule__ReferencePredicate__QualifierAssignment_2");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public QPEGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(QPEGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
