/*
 * generated by Xtext
 */
package org.omg.qpe

import org.eclipse.xtext.conversion.IValueConverterService

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class QPERuntimeModule extends AbstractQPERuntimeModule {
    /*
    override Class<? extends IValueConverterService> bindIValueConverterService() {
        return QPEValueConverterService;
    }
    */
}
