/*
 * generated by Xtext
 */
package org.omg.qpe


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class QPERuntimeModule extends AbstractQPERuntimeModule {
}
