/**
 * generated by Xtext
 */
package org.omg.qpe.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.omg.qpe.ui.AbstractQPEUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class QPEUiModule extends AbstractQPEUiModule {
  public QPEUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
