/*
 * generated by Xtext
 */
package org.omg.qpe.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class QPEUiModule extends AbstractQPEUiModule {
}
