/**
 * generated by Xtext
 */
package org.omg.qpe.ui.contentassist;

import org.omg.qpe.ui.contentassist.AbstractQPEProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class QPEProposalProvider extends AbstractQPEProposalProvider {
}
