/**
 * generated by Xtext
 */
package org.omg.qpe.validation;

import org.omg.qpe.validation.AbstractQPEValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class QPEValidator extends AbstractQPEValidator {
}
